### ISSUE TITLE
Feature: Device filter on Windows

### ISSUE THREAD

**Issue by reidprichard** [houmain/keymapper#107]
Cool project!
I'm just wondering if implementation of the `device` filter in Windows is planned in the near term. My workflow depends on having per-device and per-application keybinds, and being able to do that all in a single cross-platform program would be incredible. 

I'm currently using a combination of [kmonad](https://github.com/kmonad/kmonad) and [keyd](https://github.com/rvaiya/keyd) on Linux and [AutoHotkey](https://github.com/AutoHotkey/AutoHotkey) with [AutoHotkey Interception](https://github.com/evilC/AutoHotInterception) on Windows and man is it annoying to keep up with all that.

There are a lot of remapper tools out there, but AFAIK yours is the only one that simultaneously allows device- and application-specific binds. Having both of those work cross-platform would be a killer feature. (Some sort of layering feature would be very cool too, but I think that can be worked around more easily.)

**Comment by houmain** [comment]
Hi, thanks!
Yes, being able to filter by device also on Windows would be a valuable addition.
I will try to implement it!

**Comment by houmain** [comment]
Hi, this will be available in the upcoming 4.0.0 release which is already documented and testable in the `next` branch. It is also using the Interception driver, with its shortcoming (especially this open [issue](https://github.com/oblitum/Interception/issues/25)).

**Comment by kbilsted** [comment]
could be fun to play around with two numpad-keyboards and mapping them as one split keyboard

**Comment by Zireael07** [comment]
@kbilsted This is exactly what I am going to be doing soon ;)
