### ISSUE TITLE
Keys BrowserBack and BrowserForward only work without a scope block

### ISSUE THREAD

**Issue by ristomatti** [houmain/keymapper#108]
I've only got a Linux box to test, so this might not occur on other OS's. 

Example config:

```
AltGr = AltRight
_Alt = !ControlLeft !ControlRight !MetaLeft !MetaRight !AltGr AltLeft

# Defined here works
BrowserBack     >> AltLeft{ArrowLeft}
BrowserForward  >> AltLeft{ArrowRight}

[default]
  # Defined here doesn't
  BrowserBack     >> navigate_back
  BrowserForward  >> navigate_forward

  navigate_back     >> _Alt{ArrowLeft}
  navigate_forward  >> _Alt{ArrowRight}
```

(I've got the keys mapped on an alternate layer using QMK)

**Comment by houmain** [comment]
These two configurations lead to the exact same internal representation of the configuration. So it is not logical that they behave differently. You could reproduce it with just these configurations and nothing else?

**Comment by ristomatti** [comment]
Nope it appears not, not even with the updated example (it was typed in a hurry). I figured out now what the issue was. I had these before the default block in the example config (without the log statements):

```
# Keychron K15 Pro media keys
[device=KeyboardK15ProMedia]
  Any >> log["media"] Any

# Keychron K15 Pro system keys
[device=KeyboardK15ProSystem]
  Any >> log["system"] Any

# Keychron K15 Pro mouse buttons
[device=KeyboardK15ProMouse]
  Any >> log["mouse"] Any
```

It turned out that my keyboard sends those particular key events from `Keychron Keychron K15 Pro Consumer Control` and not the one I've set most of the mappings to `Keychron Keychron K15 Pro Keyboard`. I added those at some point just to be specific.

So, it was a case of PEBCAC. Sorry!
