### ISSUE TITLE
Nix OS package release

### ISSUE THREAD

**Issue by rp1231** [houmain/keymapper#111]
It would be nice to have a release for nixos as well.
Thanks

**Comment by arutonee1** [comment]
It's already [in nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/tools/inputmethods/keymapper/default.nix).

**Comment by arutonee1** [comment]
@rp1231 Run `sudo keymapperd` in the background, and `keymapper` (as a normal user)- it will load the config in `./keymapper.conf` by default.

**Comment by arutonee1** [comment]
@rp1231 I'd personally have an alias or script to just run keymapperd whenever the session starts (this is WM/DE-dependent), or even alias `keymapper` to `sh -c 'keymapperd & keymapper'`

**Comment by arutonee1** [comment]
You can also create your own NixOS service under `systemd.user.services` ([this](https://nixos.wiki/wiki/Extend_NixOS) might be helpful)

**Comment by Azarattum** [comment]
The package it pretty out of date though, even in the unstable branch (still v3.0.0). Is it maintained?

**Comment by arutonee1** [comment]
@Azarattum Maybe email the maintainer (7rat13@gmail.com) to ask? Updating the package yourself isn't very difficult either.
