### ISSUE TITLE
why are there 2 exefiles

### ISSUE THREAD

**Issue by kbilsted** [houmain/keymapper#117]
what is the reasoning behind having both keymapper.exe and keymapperd.exe 

I ask because when using the keymapper at a workplace I can imagine many places where if you install a keylogging service that also opens a port for remote control, can be hard to argue for. A scan toolk can easily identify it as a trojan program and you'd have to argue for scan policy changes etc etc

since im not sure what the kind of traffic is betwen the two executables are, Im not sure if it makes sense to suggest an argument to disable port listening, which then may lead to a more restricted user experience. Perhaps all errors are just in a logfile rather than a notification, perhaps you cannot pause the service only kill it etc etc

**Comment by houmain** [comment]
The main motivation for two executables was that: 

- one part of the system needs elevated privileges to intercept physical key presses and inject virtual key presses (keymapperd),
- and one part which needs to know which window of the currently logged in user has the focus (keymapper). More recently the feature to execute terminal commands was added, which should also be run without elevated privileges.

So for security and simplicity reasons these tasks are executed by separate processes running with the required permissions. 
The communication between these processes is kept as minimal as possible. keymapper just informs keymapperd about the configuration and the focused window. keymapperd informs keymapper about the terminal command to execute. For this only a few indices are transferred. Key presses are never transferred.
Furthermore Unix domain sockets are used for the interprocess communication (even on [Windows](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/)), so this does not need any opened ports and allows only communication between processes on the same machine.

**Comment by kbilsted** [comment]
But since both processes are needed how is this safer than if it was one process only

**Comment by houmain** [comment]
Because the critical part, the process with the elevated privileges only does what it really has to do. It does not read some file from the filesystem and does not launch processes, which would also have elevated privileges.
Also simplicity was a motivation. On Linux and MacOS the daemons are strictly separated from the GUI and cannot simply determine which window some user has focused.

**Comment by kbilsted** [comment]
Ok many thanks. Consider adding your explanation to the readme. It explains a lot.
