### ISSUE TITLE
[Bug] Assertion error logged when keymapper starts (v4.1)

### ISSUE THREAD

**Issue by ristomatti** [houmain/keymapper#131]
After I upgraded to version 4.1, I get an assertion error `gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' faile` every time I start `keymapper`. 

It doesn't seem to affect anything though.

**Comment by houmain** [comment]
It is likely one of these GTK messages which can be safely ignored.

**Comment by ristomatti** [comment]
If it's not originated from your code, I definitely agree. I'll close this.
