### ISSUE TITLE
Possible to hide the tray icon?

### ISSUE THREAD

**Issue by mfinelli** [houmain/keymapper#133]
Hi, would it be possible to hide the tray icon (at runtime, without needing to build without tray icon support)? It clutters my desktop and at the moment doesn't provide me any utility as my configuration, devices, etc are very stable.

Thanks for great software

Cheers
Mario

**Comment by ristomatti** [comment]
There's a flag for it: `keymapper --no-tray`

**Comment by mfinelli** [comment]
Works perfectly, thanks!
