### ISSUE TITLE
request: flag to allow changing config file

### ISSUE THREAD

**Issue by kbilsted** [houmain/keymapper#135]
Many times a day i switch config file - it would be great with a command line flag that allows changing the config rather than telling me an instance is already running ;)

**Comment by ristomatti** [comment]
How about just make a script to do this.

Strategies:
- make a script/alias that kills all `keymapper` proceses, then starts with the defined config
- write one generic script that takes the config file as an argument and does the above
- don't specify a config and replace the default config with some other config by copying it over the default config

**Comment by ristomatti** [comment]
Based on a quick search, on Windows you should be able to do `taskkill /F /IM keymapper.exe /T` in a script. If the config files are static, perhaps you could swap them using a keybinding done in Keymapper itself? :grin: 

If I needed to do that, I'd make ~/.config/keymapper.conf a symlink, then replace it with e.g.

```toml
Meta{F1} >> $(ln -sf path_to_config_a.conf ~/.config/keymapper.conf)
Meta{F2} >> $(ln -sf path_to_config_b.conf ~/.config/keymapper.conf)
```

**Comment by kbilsted** [comment]
Many thanks those a good work arounds. Id still prefer the tool to support it if easy to implement;)

**Comment by ristomatti** [comment]
I find it a bit unconventional for a running app to replace itself. Either you allow running multiple instances at the same time or not.

If @houmain thinks this would make sense to add, I'd suggest this would feel more intuitive/correct if it were done through `keymapperctl`:

```
keymapperctl --replace-config <file>
```

Alternative verbs: `set`, `swap`, `change`. I think it should convey the running config will get flushed. Using `keymapperctl` would also avoid having to think if the `--update` or `--verbose` should be handled.

**Comment by kbilsted** [comment]
Yes its a matter of how portable it should be.. how many scripts etc to drag around.. anyway its just an idea :-)

**Comment by houmain** [comment]
I will try to add a `keymapperctl --set-config <file>`.
I intend to keep the configurations in the cache, so they do not have to be parsed again and can be switched quickly.

**Comment by kbilsted** [comment]
parsing delay is not something I've noticed at all!

**Comment by houmain** [comment]
This is available in 4.1.3 and a really cool feature. Now I can quickly switch between my own configuration and the ones others want me to try out. Thanks!

**Comment by kbilsted** [comment]
Great

**Comment by ristomatti** [comment]
This is actually really convenient. Especially when combined with the new tray icon.

I just swapped the config to the repro on #138, but could not open an editor with the remapped keys. No problem, just disable the mappings from the tray icon, start the editor for testing and re-enable Keymapper.

**Comment by ristomatti** [comment]
While reverting back to my original config after doing the above, I noticed a small bug. To be able to type the path of the default config, I disabled Keymapper from the tray icon. This  reversed the behavior of the tray icon. When the toggle is enabled, my config loads and vice versa.
