### ISSUE TITLE
4.1.2 deb won't run on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Zireael07** [houmain/keymapper#136]
Spews errors about libxkbcommon and while those can be rectified, it also spews errors about glibc (IIRC it tried looking for 2.30, 2.32 and 2.34).

Nothing in README about a compat breakage, trying to identify which version is the one that breaks. So far got up to 3.0.0 which works.

**Comment by ristomatti** [comment]
Yep it doesn't. But you can build it yourself. 

```
# Install dependencies (you might need others as well, this list might not be exhaustive)
sudo apt install libappindicator3 libdbus-1-dev libdbus-glib-1-dev libdbusmenu-glib-dev libgtk-3-dev libqt5x11extras5-dev libudev-dev libusb-1.0-0-dev libwayland-dev libx11-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev

# Configure (this will tell you if some lib is still missing, install them and run again
# until it passes cleanly)
cmake -B ./build -DENABLE_WAYLAND=false`

# Build
cmake --build ./build --config Release

# Package as DEB
cpack -G DEB ./build --config ./build/CPackConfig.cmake

# Install
sudo apt install ./keymapper-4.1.2-Linux.deb
```

I also did install a newer CMake from this PPA but I'm not sure if it was necessary: https://apt.kitware.com/

Alternatively, you can try using the DEB i've built if you trust a package from a random dude: [keymapper-4.1.2-ubuntu20.04.zip](https://github.com/houmain/keymapper/files/15129975/keymapper-4.1.2-ubuntu20.04.zip). It's zipped as GitHub does not allow `.deb` as attachment.

**Comment by Zireael07** [comment]
Building is a no-go here since it's a company laptop (same goes for using a random person's deb)

**Comment by ristomatti** [comment]
Running Ubuntu 20.04 is not great for getting anything recent these days. I'm sticking to it until I get a new work laptop. Curious to know why compiling is a no go? You can do it with the packages available on the main Ubuntu repository.

**Comment by houmain** [comment]
Yes, the 3.0.0 packages were the last ones that were built with Ubuntu 20.04. I had to upgrade the build system to Ubuntu 22.04 since 20.04 did not have libxkbcommon >= 1.0, which is required for the character typing under Wayland.

**Comment by houmain** [comment]
I hope you get by with an older version on the mentioned system.
Maybe you can also boot a live image in a VM and build the current version using the ristomati's guide?

**Comment by Zireael07** [comment]
Company rules forbid compiling anything as well as installing anything unapproved

**Comment by ristomatti** [comment]
You got same strange rules over there if a package downloaded from the same repository would be ok. Given how strict the policy is, to me it sounds like any app running root and listening for key events could never get approved. But regardless, I feel the pain, I've worked under a strict policy at one point during my career.

**Comment by Zireael07** [comment]
@ristomatti They approved debs from this repo as I insisted I need keymapper specifically for accessibility reasons (which is true as no other app can do all the things it does)

**Comment by ristomatti** [comment]
I can confirm the flag is no more needed, and that I can now install the `deb` file on the releases. @Zireael07 you should be good to go. :-1:
