### ISSUE TITLE
Volume control keys not working with scan code

### ISSUE THREAD

**Issue by RiccardoBarbieri** [houmain/keymapper#140]
I created the following mappings:
```
volumeMuteCmd = $(/home/riccardoob/scripts/audio-polybar/pulseaudio-control togmute) ^    
volumeDownCmd = $(/home/riccardoob/scripts/audio-polybar/pulseaudio-control --volume-max 130 down) ^
volumeUpCmd = $(/home/riccardoob/scripts/audio-polybar/pulseaudio-control --volume-max 130 up) ^

173 >> volumeMuteCmd
174 >> volumeDownCmd    
175 >> volumeUpCmd
```
to launch the scripts when I press the volume controls but it doesn't seem to work.
I tested with other mappings such as 
`173 >> Backspace`
to understand if the problem was with the command definitions but it still does not work.
I tried using the **event names** and it works.

How can I get it to work with the **scan codes**? In the documentation it is not specified how to actually use them.

**Comment by RiccardoBarbieri** [comment]
@ristomatti yes, I used the web tool suggested in the documentation to get the codes.

**Comment by houmain** [comment]
The scan codes on windows are:
  AudioVolumeMute   = 0xE020
  AudioVolumeDown  = 0xE02E
  AudioVolumeUp      = 0xE030

You can find them [here](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values):
or in the [source](https://github.com/houmain/keymapper/blob/main/src/runtime/Key.h#L215)
But there should be no need for the scan codes when the keys have names (which you can get [here](https://www.toptal.com/developers/keycode)).

**Comment by ristomatti** [comment]
@RiccardoBarbieri Just to clarify, the key codes shown on https://www.toptal.com/developers/keycode aren't the same as scan codes, I got confused by this initially also. The site is only useful for finding the key names used by Keymapper.

To find out the scan codes you'll need some other tool. I'm not on Windows so I don't know which one to recommend. Based on a quick search you'll find one easily in case you run across a key that's not recognized by Toptal.
