### ISSUE TITLE
How to disable Caplock or any key I want?

### ISSUE THREAD

**Issue by harrytran998** [houmain/keymapper#141]
Thank for your amazing project! Can you guide us how to do like the title said?

**Comment by ristomatti** [comment]
It should be enough to put this to your config:

```
CapsLock >>
```

A popular option is to turn it into a Control key:

```
CapsLock >> Control
```

**Comment by harrytran998** [comment]
Thank for your suggest, it worked!

Here is my config for anyone want to map HJKL + Caplock in `keymapper.conf`

```bash
CapsLock >>
CapsLock{H} >> ArrowLeft
CapsLock{J} >> ArrowDown
CapsLock{K} >> ArrowUp
CapsLock{L} >> ArrowRight
```
