### ISSUE TITLE
Need to re-press Alt when used in combination with certain keys

### ISSUE THREAD

**Issue by rp1231** [houmain/keymapper#147]
I'm using keymapper in combination with komorebi, a tiling window manager.
For keyboard shortcuts such as Alt + { Letter || Number Keys }
I can just keep Alt pressed and the key combinations keep working fine.
But when I have Alt pressed and then I press a key such as eg. Tab or the F row keys,
I need to re-press the Alt key.
Hope I've explained this well.
Thanks

**Comment by ristomatti** [comment]
Post your config, otherwise it's difficult to debug.

**Comment by ristomatti** [comment]
In many of the mappings you've got a space after the modifiers, is it intentional (e.g. you press the following key in sequence and not while holding the modifiers down)?

**Comment by ristomatti** [comment]
To clarify my question, is this what you intended to do:

```
# Workspaces
Alt 1                 >> $(komorebic focus-workspace 0)
Alt 2                 >> $(komorebic focus-workspace 1)
```

...rather than this:

```
```
# Workspaces
Alt{1}                 >> $(komorebic focus-workspace 0)
Alt{2}                 >> $(komorebic focus-workspace 1)
```
