### ISSUE TITLE
Disable mouse handling

### ISSUE THREAD

**Issue by DanViTrinh** [houmain/keymapper#152]
Is it possible to disable mouse handling, my mouse behaves weirdly with keymapper. I am not using any mouse specific binds. The mouse is too sensitive with keymapper and scrolls up everytime I try to middle click.

# keymapper behavior  
https://github.com/houmain/keymapper/assets/80539964/268b8b8b-3b4b-43a4-aa9d-3e3274fd4937

# without keymapper
https://github.com/houmain/keymapper/assets/80539964/1b6a7529-e256-4507-a580-1f7566811f07

**Comment by houmain** [comment]
> I am not using any mouse specific binds.

are you sure? The mouse handling should not be enabled, when you do not have any `Button*` and `Wheel*` keys in your configuration.

I think the mouse is becoming too sensitive, because the DPI information of the virtual device does not match the rate of the movement events it forwards. Likely this cannot be fixed automatically and requires a [custom setting](https://wayland.freedesktop.org/libinput/doc/latest/faqs.html#my-mouse-moves-too-fast-even-at-the-slowest-setting). I have not tried it, but [here](https://bbs.archlinux.org/viewtopic.php?id=221980) someone was successful.

The middle click/wheel phenomenon is indeed weird.
Could you please post your configuration and the output of `sudo keymapperd -v`.

**Comment by DanViTrinh** [comment]
Not sure whats going on here: 
sudo keymapperd -v
ERROR: Initializing keymapper connection failed

My config:
# comments start with # or ; and continue until the end of a line
(ControlLeft AltLeft){Any} >> AltRight{Any}

(ControlRight AltRight){Any} >> MetaLeft{Any}

(AltRight){F} >> AltLeft{F}
(AltRight){B} >> AltLeft{B}

**Comment by houmain** [comment]
Sorry, likely `keymapperd` was already running.
So stop it first:
`sudo systemctl stop keymapperd`
and then run:
`sudo keymapperd -v`

**Comment by DanViTrinh** [comment]
Waiting for keymapper to connect      Resetting configuration
Active contexts received (1)
Updating device list
  /dev/input/event0 grabbed (Power Button)
  /dev/input/event1 grabbed (Power Button)
  /dev/input/event2 ignored (PC Speaker)
  /dev/input/event4 grabbed (Eee PC WMI hotkeys)
  /dev/input/event8 ignored (HDA NVidia HDMI/DP,pcm=3)
  /dev/input/event9 ignored (HDA NVidia HDMI/DP,pcm=7)
  /dev/input/event10 ignored (HDA NVidia HDMI/DP,pcm=8)
  /dev/input/event11 ignored (HDA NVidia HDMI/DP,pcm=9)
  /dev/input/event12 grabbed (Keychron Keychron K2)
  /dev/input/event3 ignored (HD-Audio Generic Front Mic)
  /dev/input/event5 grabbed (Keychron Keychron K2)
  /dev/input/event13 ignored (HD-Audio Generic Rear Mic)
  /dev/input/event6 ignored (HD-Audio Generic Line)
  /dev/input/event7 ignored (HD-Audio Generic Line Out)
  /dev/input/event16 ignored (HD-Audio Generic Front Headphone)
  /dev/input/event14 grabbed (Logitech MX Master 2S)
Creating virtual device 'Keymapper'
Entering update loop
Updating device list
  /dev/input/event0 already grabbed (Power Button)
  /dev/input/event1 already grabbed (Power Button)
  /dev/input/event2 ignored (PC Speaker)
  /dev/input/event4 already grabbed (Eee PC WMI hotkeys)
  /dev/input/event8 ignored (HDA NVidia HDMI/DP,pcm=3)
  /dev/input/event9 ignored (HDA NVidia HDMI/DP,pcm=7)
  /dev/input/event10 ignored (HDA NVidia HDMI/DP,pcm=8)
  /dev/input/event11 ignored (HDA NVidia HDMI/DP,pcm=9)
  /dev/input/event12 already grabbed (Keychron Keychron K2)
  /dev/input/event3 ignored (HD-Audio Generic Front Mic)
  /dev/input/event5 already grabbed (Keychron Keychron K2)
  /dev/input/event13 ignored (HD-Audio Generic Rear Mic)
  /dev/input/event6 ignored (HD-Audio Generic Line)
  /dev/input/event7 ignored (HD-Audio Generic Line Out)
  /dev/input/event16 ignored (HD-Audio Generic Front Headphone)
  /dev/input/event14 already grabbed (Logitech MX Master 2S)
  /dev/input/event15 ignored (Keymapper)
Connection to keymapper reset
Releasing all keys (2)
Resetting configuration
Ungrabbing all devices
Destroying virtual device
---------------
Waiting for keymapper to connect
^C

**Comment by houmain** [comment]
Thanks, I think I know what's going on. Some buttons of this mouse make it look like a keyboard, and so it is automatically grabbed.
The latest commit hopefully fixes this.
Are you building from source / can you install `keymapper-git` from the Arch Linux AUR, or should I create a new release so you can try it out?

**Comment by DanViTrinh** [comment]
The issue seems fixed thank you
