### ISSUE TITLE
shift handling on shift held and with multiple subsequent key presses

### ISSUE THREAD

**Issue by kbilsted** [houmain/keymapper#157]
When I press and hold `shift` and then type `j` and `j` the result is `JJ`

When using a mapping  

```
J	        >> ArrowDown
(Shift J) 	>> ControlLeft{Tab}
```

if I press and hold `shift` and then type `j` and `j` it fires a `control tab`and then a `arrowdown`.  I was expecting two `control tab`, 

Is there documentation lagging or a bug?

**Comment by houmain** [comment]
I am pretty sure that's how it is [supposed to work](https://github.com/houmain/keymapper#functional-principle). Please try
```
!Shift J        >> ArrowDown
(Shift J) 	>> ControlLeft{Tab}

```

**Comment by kbilsted** [comment]
I can get it to work with

```
(Shift J) 	>> ControlLeft{Tab}
J	        >> ArrowDown
```

when using below it doesn't work

```
J	        >> ArrowDown
(Shift J) 	>> ControlLeft{Tab}
```

but now that I found out that, I think this is already covered in the docs
