### ISSUE TITLE
documentation Context awareness

### ISSUE THREAD

**Issue by kbilsted** [houmain/keymapper#160]
it would be good if we can improve the docs at https://github.com/houmain/keymapper?tab=readme-ov-file#context-awareness

Things that we need to explain

* What are the legal values for `system`
* What is `window class` and how do you find them
* how to find input device/device_id

**Comment by houmain** [comment]
I added:

> The values of a context can be easily obtained using the Next Key Info function of the tray icon or [keymapperctl](https://github.com/houmain/keymapper?tab=readme-ov-file#keymapperctl).

And _Next Key Info_ also contains the `system` now.
