### ISSUE TITLE
Context awareness

### ISSUE THREAD

**Issue by 86Atlas** [houmain/keymapper#168]
Hi all,

I have these lines in my config:

#comments start with # or ; and continue until the end of a line
#ButtonLeft, ButtonRight, ButtonMiddle, ButtonBack and ButtonForward, the wheel is named WheelUp and WheelDown

[title = 'Path of Exile', class = 'steam_app_238960']
Control {WheelUp} >> Control {ButtonLeft}
CapsLock >> (Control ButtonLeft)

And i have been trying for a couple of days to only apply these when the window of Path of Exile (with or without the "class") is focused. I am running the kwin script as well.

Problem is that this always applies to everything and i dont know how to make it work. Any help is highly appreciated.

**Comment by houmain** [comment]
Very strange, could you start `keymapper` with the -v flag in a terminal and focus some windows and post the output here?
To see whether the configuration is really read from the file you are editing and the focused window detection is working.

**Comment by 86Atlas** [comment]
Hi!

Sure:

Detected focused window changed:
  class = 'steam_app_238960'
  title = 'Path of Exile'
  path = '/usr/share/steam/compatibilitytools.d/proton-cachyos/files/bin/wine64-preloader'
Active contexts updated
Sending active contexts (2)


However, if i focus say the dolphin window, or just my desktop, there is no change it this output

**Comment by houmain** [comment]
I tried it with the latest Ubuntu/Wayland/KDE and could reproduce it was no longer working.
This updated [main.js](https://raw.githubusercontent.com/houmain/keymapper/1514a44b058a6b1b958d290b7b4be15f88431e9f/extra/share/kwin/scripts/keymapper/contents/code/main.js) in in /usr/share/kwin/scripts/keymapper/contents/code/ should make it work again. It will be in the next release. 
Thanks for reporting!

**Comment by 86Atlas** [comment]
Glad i could help!

**Comment by houmain** [comment]
This is now in the 4.7.0 release.
