### ISSUE TITLE
[Feature Request] Ability to blacklist applications 

### ISSUE THREAD

**Issue by YMan84** [houmain/keymapper#17]
I would love the ability to blacklist certain applications from triggering all shortcuts. I use AnyDesk and NoMachine constantly at home and at work, and my remote machines have a synced up keymapper configuration/autohotkey shortcuts, but i'm not able to utilize them because keymapper on my local machine take priority. 

Thanks for the fantastic work. This is by far the best and easiest shortcut manager that i've had the pleasure of using.

**Comment by houmain** [comment]
Good idea. I am already thinking about how this could manifest in the configuration.

Thank you very much for your kind words!

**Comment by houmain** [comment]
With the latest commit (6f0fc397ceaf48b855f3cbc75844843da9aedbbe) this is possible. 
Now multiple contexts can be active at once and contexts can be defined even before the default mappings by returning to the default context with `[default]`:
```
[title="AnyDesk"]
Any >> Any

[default]
A >> B
```
The mappings are still searched in consecutive order. For 'AnyDesk' it would immediately find the `Any >> Any` mapping, which simply forwards the input.
