### ISSUE TITLE
[Feature Request] Let keymapperctl work for all keys

### ISSUE THREAD

**Issue by tonyatpeking** [houmain/keymapper#170]
Currently keymapperctl can change whether a virtual key is presses / released, is it possible to extend the scope so that it works for all keys / input expressions?

For example 
`keymapperctl --press A`
`keymapperctl --press A{B}`

Ideally this would simulate an actual keyboard press and go through all the rules in keymapper.conf, so  `keymapperctl --press A` would trigger whatever `A` is mapped to, and just emit `A` if it is not mapped.

**Comment by ristomatti** [comment]
I've been thinking about this also. Out of curiosity, what would the use case be?

**Comment by tonyatpeking** [comment]
## Use case
Move all 'business logic' to external program (python). 

## Reason 
Using a config language to program gets messy.

## Current state
One way communication is possible (see details below).

## After proposed change

Full two way communication with external program. The flexability of a programming language will open up many possibilities without bloating keymapper itself (see potential uses)

## Details
Currently I can do one way communication with python. I use the $() syntax to send messages to a named pipe or a socket that python reads. The full context state can easily be mirrored because we can do `ContextActive >> PIPE_ENTER_CONTEXT ^ PIPE_EXIT_CONTEXT`.
Some other projects use a TCP server for communication (after some shallow digging I think they also only support layer changes as opposed to arbitrary key triggers) https://github.com/jtroo/kanata?tab=readme-ov-file#similar-projects
Keymapper seems like the only one that is cross platform AND context aware.

## Potential uses
- Macro recording / Dynamic key-binding
  - Say I'm using a program that I know I will only use once in my lifetime, I want to bind a shortcut but I don't want to clutter my keymapper.conf. I can record a one time macro.
- Visual feedback and discoverability.
  - With the shortcuts stowed away in python it will be possible to have a gui that allows for:
    - Show layer I'm currently on.
    - Show what key does what on current layer.
    - Show what key was just pressed.
    - Edit what key does what directly in the gui
  - Something similar to keymapp (yes they named it that, sadly not opensource) https://www.youtube.com/watch?v=ZxAGHQh36LI
  - I have an ergodox so I can use keymapp and all but because everything is on the hardware level it is not context aware.

**Comment by ristomatti** [comment]
I've had very similar thoughts actually, but I couldn't have put them into words this well :+1:. Both recording macros and indicating the active "layer" have crossed my mind. Have you BTW read the original discussion (#103) that lead to `keymapperctl` getting added?

> I have an ergodox so I can use keymapp and all but because everything is on the hardware level it is not context aware.

I also use QMK remappable keyboard (you've probably already noticed from my configs), but like you said, the lack of context awareness greatly reduces the possibilities. So much in fact, that I'm only using a small set of my QMK remaps I spent a lot of time coming up with. And even those I'm planning to migrate over to Keymapper over time. I've also found Keymapper to have even better control over timings for instance, so performance/latency is not an issue either.

> Show what key was just pressed. (already possible)

If you refer to `keymapperctl --next-key-info`, another method (for debugging) I've found very useful is by using `evtest`. I've defined a `udev` rule (described [here](https://github.com/houmain/keymapper/issues/85#issuecomment-1899406976)) that makes Keymapper's virtual input device always available at `/dev/keymapper`.  This allows me to see the input events send out by keymapper:

```bash
alias km-scan='sudo evtest /dev/keymapper | rg -v '\''(REL_X|REL_Y|SYN_REPORT)'\'
``` 


Aside: Great to see others making use of Keymapper's more advanced features! It sheds of some of the guilt I've been feeling for requesting these. 😅

**Comment by ristomatti** [comment]
Even though not a solution to this, have you noticed the recently added `--type` option?

```
$ keymapperctl --help | rg type
  --type "string"       types a string of characters.
```

I was going to suggest experimenting with `xdotool` as well but then remembered it's quite a hit and miss. I just tested if I can get it to type `AltRight{A}` which I've mapped to `AltRight{Q}` in Keymapper (`ä` on `us+altgr-intl` layout) with `xdotool key Alt_R+a`. It didn't type anything. I then tried `xdotool key Alt_R+q` and even that didn't work.  While those didn't work, `xdotool key Control+c` did work!

As a cherry on top, I tried one more time:

```
$ xdotool sleep 2 keydown Alt_R sleep 0.5 type "a" keyup Alt_R
```

...followed up by focusing a text editor. It didn't seem to do anything at first but then I realized `AltRight` is stuck held down. And it remained stuck even after 1) pressing the key, 2) unplugging/replugging my keyboard, 3) pausing and resuming Keymapper mappings using the tray icon. With the key stuck down, I couldn't type `xdotool --clearmodifiers` to fix it. WTF? I had to **ssh to my computer from my phone** to run the damn command :cursing_face:! Before doing that I checked if `xdotool` was running, and it was not...

**Comment by tonyatpeking** [comment]
Thanks so much for the info dump. Will try all the things you mentioned.
I often find the github issues page to have hidden gems not in the docs. 
Yes I have seen `xdotool` and other projects. I would prefer not to use an additional program if possible as that is an added point of failure.

**Comment by tonyatpeking** [comment]
lol that is so funny and can relate to that. I've also soft locked myself out countless times messing around with keybindings 🤣

**Comment by houmain** [comment]
Hi, this is testable in 4.8.0.

There are now two new `keymapperctl` operations `--input` and `--output` for injecting key presses. e.g.:

```keymapperctl --input A{B}```

with `--input` the mappings are applied as if the sequence came from an input device,
with `--output` the sequence is output as if it was generated by keymapper.

**Comment by ristomatti** [comment]
So `--output` sends out the given key sequence through Keymapper's virtual device in verbatim. E.g. it can be used similarly as `xdotool` but without the WTF factor? It think it'll be more useful for my use cases. Good planning ahead!

**Comment by houmain** [comment]
Yes, right. Hopefully without too many WTFs.

**Comment by ristomatti** [comment]
Sorry forgot to report back! I did some quick testing then and both features worked as expected. It handled even `? X Y Z' type of mappings. Only nitpick is the fact aliases aren't recognized, but `keymapperctl` did correctly exit with code `1` if one was used.

@tonyatpeking In case you get your macro recording (or your other plans) implemented, it would be cool if you'd post how you ended up doing that in the [Show and tell](https://github.com/houmain/keymapper/discussions/categories/show-and-tell) section!
