### ISSUE TITLE
ERROR: Creating virtual device failed on Ventura

### ISSUE THREAD

**Issue by clyra** [houmain/keymapper#178]
Hi,

I'm trying to compile/run version 4.8.2 of keymapper on a osx ventura. Running "sudo keymapperd -v" and keymapper I got this on keymapperd output:

````
Waiting for keymapper to connect
Resetting configuration
Active contexts received (1)
Updating device list
  'Keyboard K380' ignored
  'USB Receiver' ignored
  'USB Receiver' ignored
  'USB Receiver' ignored
  'BTM' ignored
  'Headset' ignored
Updating device list
  'Keyboard K380' grabbed
  'USB Receiver' ignored
  'USB Receiver' ignored
  'USB Receiver' grabbed
  'BTM' ignored
  'Headset' ignored
Creating virtual device 'Karabiner'
Karabiner connected
ERROR: Creating virtual device failed
Ungrabbing all devices
````

Maybe this is related to a recent change on karabiner, since i just updated to version 15.2.0 (which, i guess, use the last version of the virtualhiddevice, which has a "breaking change"):

https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/releases

Also, it seems that the grab-device is not working as expected because my config should only allow the K380 Keyboard:

````
@skip-device /.*/
@grab-device "Keyboard K380"
````

**Comment by houmain** [comment]
Version 4.9.0 was updated to [Karabiner-DriverKit-VirtualHIDDevice/releases](https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/releases) 5.0.0, which is used by Karabiner-Elements 15.x.x.
