### ISSUE TITLE
client version mismatch detected

### ISSUE THREAD

**Issue by clyra** [houmain/keymapper#185]
Hi,

Sorry to bother so soon... OSX version is now building, but while trying to run it I got a "ERROR: client version mismatch detected". To be sure that I'm now running the new version I deleted the sources directory and git cloned the repository again. Build works as expected with "cmake -B build" and "cmake --build build". I also created a empty keymapper.conf to ensure that I'm running the simplest config. I also closed karabiner-elements app. Here is what happens:

![Captura de Tela 2024-11-15 às 22 32 34](https://github.com/user-attachments/assets/47ddfcb8-defa-40ea-8b51-1464ec0b179f)

**Comment by houmain** [comment]
Hi,
Was maybe still an old `keymapper` launchd agent running, which connected to `keymapperd` before the new one?
The agent could be removed with `sudo keymapper-launchd remove`.

**Comment by clyra** [comment]
> Hi, Was maybe still an old `keymapper` launchd agent running, which connected to `keymapperd` before the new one? The agent could be removed with `sudo keymapper-launchd remove`.

I did tried that too, but in the end, it was something even more "obvious". There was a keymapperd binary somewhere in the $PATH, and I forgot the "./". Thanks, and closing!

**Comment by clyra** [comment]
working as expected.
