### ISSUE TITLE
App specific switching issue

### ISSUE THREAD

**Issue by IcarusOne** [houmain/keymapper#191]
Arch KDE 6.2 Wayland

[title = "app"]
1 >> 2

[default]
1 >> 1

Switching to the app works, but when switching away from the app, profile does not switch unless focusing specific apps.

Tabbing from app to firefox, dolphin, konsole or clicking desktop does not switch. Tabbing to spotify or discord causes the switch though.

**Comment by ristomatti** [comment]
Does clicking the desktop unfocus the window? On i3wm (X11) it's not possible at least. If I run `xprop` and click the desktop area, it has properties but it doesn't have either of these properties set:

- `WM_CLASS` - used for matching by class
- `WM_NAME` - used for matching by title
 
Tabbing to another app should definitely deactivate the context thought.

**Comment by IcarusOne** [comment]
Clicking the desktop does unfocus the window.

I added more app profiles, and it seems it will switch between the apps without issue, and again will not switch away from last used app if I tab or interact with desktop or some apps.

I tested with some other apps, and only a couple trigger the switch. Bottles and Lutris don't, Discord and Spotify do. I'm also unable to make a profile specific to Firefox, as I assume the title changes based on tabs open?

**Comment by ristomatti** [comment]
For Firefox, try using a class matcher instead:

```ini
[class = /firefox/i]
1 >> 3
```

Out of curiosity, does adding this help with the stuck context:

```ini
[title != "app"]
1 >> 1

[title = "app"]
1 >> 2
```

**Comment by IcarusOne** [comment]
Neither worked

**Comment by ristomatti** [comment]
What output do you get from running this and then selecting Firefox window?

```
xprop | grep -E '^WM_(NAME|CLASS|TITLE|ROLE|INSTANCE)'
```

...I haven't used Wayland though, `xprop` might be X11 specific.

**Comment by IcarusOne** [comment]
That command didn't work, but "xprop" output

`
GAMESCOPE_COMPOSITE_FORCE(CARDINAL) = 0
GAMESCOPE_COMPOSITE_DEBUG(CARDINAL) = 0
GAMESCOPE_ALLOW_TEARING(CARDINAL) = 0
GAMESCOPE_RESHADE_TECHNIQUE_IDX(CARDINAL) = 0
GAMESCOPE_RESHADE_EFFECT(UTF8_STRING) = 
GAMESCOPE_DEBUG_HDR_HEATMAP(CARDINAL) = 0
_NET_WORKAREA(CARDINAL) = 0, 0, 3840, 2160
_NET_SHOWING_DESKTOP(CARDINAL) = 0
GDK_VISUALS(INTEGER) = 921, 788
_QT_GET_TIMESTAMP(INTEGER) = 
AT_SPI_BUS(STRING) = "unix:path=/run/user/1000/at-spi/bus_1"
RESOURCE_MANAGER(STRING) = "Xcursor.size:\t24\nXcursor.theme:\tbreeze_cursors\nXft.antialias:\t1\nXft.dpi:\t96\nXft.hinting:\t1\nXft.hintstyle:\thintslight\nXft.rgba:\trgb\n"
_KDE_NET_WM_BACKGROUND_CONTRAST_REGION(_KDE_NET_WM_BACKGROUND_CONTRAST_REGION) = 0x0
_KDE_NET_WM_BLUR_BEHIND_REGION(_KDE_NET_WM_BLUR_BEHIND_REGION) = 0x0
_KDE_WINDOW_HIGHLIGHT(_KDE_WINDOW_HIGHLIGHT) = 0x0
_KDE_SLIDE(_KDE_SLIDE) = 0x0
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x1200007, 0x1600005, 0xae00012, 0x2c00004, 0x6e00039, 0x2a00001
_NET_CLIENT_LIST(WINDOW): window id # 0x1200007, 0x2c00004, 0x1600005, 0x6e00039, 0xae00012, 0x2a00001
_NET_DESKTOP_GEOMETRY(CARDINAL) = 3840, 2160
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x0
_NET_DESKTOP_NAMES(UTF8_STRING) = "Desktop 1"
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_DESKTOP_LAYOUT(CARDINAL) = 0, 1, 1, 0
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 1
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x200001
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_NUMBER_OF_DESKTOPS, _NET_DESKTOP_GEOMETRY, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_ACTIVE_WINDOW, _NET_WORKAREA, _NET_DESKTOP_LAYOUT, _NET_CLOSE_WINDOW, _NET_RESTACK_WINDOW, _NET_SHOWING_DESKTOP, _NET_WM_MOVERESIZE, _NET_MOVERESIZE_WINDOW, _NET_WM_NAME, _NET_WM_VISIBLE_NAME, _NET_WM_DESKTOP, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_STATE, _NET_WM_STATE_MODAL, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SHADED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _KDE_NET_WM_STATE_SKIP_SWITCHER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_STAYS_ON_TOP, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_STATE_FOCUSED, _NET_WM_STRUT, _NET_WM_STRUT_PARTIAL, _NET_WM_ICON_GEOMETRY, _NET_WM_ICON, _NET_WM_PID, _NET_WM_PING, _NET_WM_USER_TIME, _NET_STARTUP_ID, _NET_WM_WINDOW_OPACITY, _NET_WM_FULLSCREEN_MONITORS, _NET_WM_ALLOWED_ACTIONS, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_FRAME_EXTENTS, _KDE_NET_WM_FRAME_STRUT, _NET_WM_FULL_PLACEMENT, _KDE_NET_WM_ACTIVITIES, _KDE_NET_WM_SHADOW, _NET_WM_OPAQUE_REGION, _GTK_FRAME_EXTENTS, _GTK_SHOW_WINDOW_MENU
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
`

My apologies if I'm not providing better info. Windows killed itself again and this is my first proper attempt at linux.

**Comment by IcarusOne** [comment]
Another troubleshoot attempt I made was with the Kwin script. Adding connectWindowDeactivated. Did not help

**Comment by ristomatti** [comment]
Perhaps that will help @houmain debug the issue.

> Windows killed itself again and this is my first proper attempt at linux.

Straight into the deep end with Arch. :muscle:

**Comment by houmain** [comment]
> Tabbing to spotify or discord causes the switch though.

Maybe these apps are still using XWayland, which are handled by the X11 code, not the KWin script.

Are you sure the KWin script is running? If yes, could add some [print](https://develop.kde.org/docs/plasma/kwin/) output and tell if the `connectWindowActivated` is called whenever you switched the focus.
Thanks for troubleshooting!

**Comment by IcarusOne** [comment]
Ty for the insight. It seems it was a problem with KDE and scripts. It refused to enable any script despite the GUI showing enabled.

Fixed by reinstalling KDE.
