### ISSUE TITLE
Key suppression issue, at least on windows

### ISSUE THREAD

**Issue by developer91234** [houmain/keymapper#192]
```
Meta{G} >> K

```

Brings up the gamebar. Variations like additionally mapping it to null `Meta{G} >>`, or adding `^` anywhere in the output don't do anything, the gamebar still comes up.

**Comment by developer91234** [comment]
However Meta{G} >> Meta{I} does suppress the gamebar and correctly opens the system settings.

**Comment by houmain** [comment]
Interesting observations, especially the second one!
This shortcut seems to be handled at a lower level of the OS, maybe so it even works in games which are using raw input? I doubt there is anything that can be done about that. Other than using the [Interception driver](https://github.com/houmain/keymapper#virtual-device-driver).
Mapping it to another Meta combination like `Meta{J}`, which does nothing, might also work:

`Meta{G} >> Meta{J} K`

**Comment by developer91234** [comment]
Perhaps but for all practical intents and purposes the shortcut is suppressible, as demonstrated.

**Comment by developer91234** [comment]
Tangentially related, I was trying to remap a stupid lock key on my keyboard, one that was emitting multiple keys, and couldn't understand what it was doing until I tested it with this software: https://dennisbabkin.com/kbdkeyinfo/

Other software just gets the last emitted code, misidentifies the keys, doesn't deal with key up/down, or just plain loses focus before it has a chance to capture anything. It's really the best scanner I've found for Windows.

**Comment by developer91234** [comment]
Actually, testing with this software produces as odd result for the meta+G combo, it just registers meta and fails to capture G.
