### ISSUE TITLE
OR statements in contexts

### ISSUE THREAD

**Issue by developer91234** [houmain/keymapper#193]
Would be nice to do something like `[class=X | path=Y]` for added cross platform compatibility - classes make more sense in Linux, while paths make more sense in Windows.

Maybe it's possible to do via stages or something, I still don't really get what a state is or how to implement it. If a named stage can be used to store a block of mapping, then a"inserted" anywhere in the conf via its name, then this might work, even if it would be verbose. But again, I don't know what states are.

**Comment by houmain** [comment]
This is already possible, as indicated in the README with this sample:
```
[device = "Some Device Name"] # consecutive blocks share mappings
[device = "Some Other Device"]
```

**Comment by ristomatti** [comment]
> Maybe it's possible to do via stages or something, I still don't really get what a state is or how to implement it. If a named stage can be used to store a block of mapping, then a"inserted" anywhere in the conf via its name, then this might work, even if it would be verbose. But again, I don't know what states are.

I assume you're referring to "stages" when you say "states" here. Adding the `[stage]` block at any point in the config can be thought of like you would run several copies of Keymapper running on top of each other. The resulting output prior to `[stage]` will be  outputted to the part after it.

AFAIK, you can add as many of them as you like, but I would not recommend adding more than one. The concept originated from an issue thread on creating an alternative keyboard layout. If you wished to do that, prior to `[stage]`, it would have been difficult to make sense of the consequent mappings.

E.g. lets say you for some reason wanted to swap `ControlLeft` and `AltLeft` (perhaps even swapping the keycaps), you could then use the swapped keys on the config w/o mental gymnastics:

```ini
ControlLeft >> AltLeft
AltLeft >> ControlLeft

# AltLeft refers to the physical left Alt key
AltLeft{K} >> Meta{Space}  # AltLeft{K} sends Meta{Space}

[stage]
# AltLeft refers to the swapped physical left Control key
AltLeft{K} >> Meta{Space}  # Control{K} sends Meta{Space}
```

I hope this helped!

**Comment by developer91234** [comment]
Yeah I get it now. It's more readily apparent from the Control <-> Alt swapping example, which is a common use case, than from the readme's letter swapping example.
