### ISSUE TITLE
Remapping an unidentified "Fn" key

### ISSUE THREAD

**Issue by developer91234** [houmain/keymapper#194]
```
{
 "key": "Unidentified",
 "keyCode": 255,
 "which": 255,
 "code": "WakeUp",
 "location": 0,
 "altKey": false,
 "ctrlKey": false,
 "metaKey": false,
 "shiftKey": false,
 "repeat": false
}
```

Is it possible to remap this without the driver? I does emit the code "WakeUp" but reassinging this key via `Wakeup >> Some_Key` doesn't work.

**Comment by houmain** [comment]
Thanks, I will add it.
For now you can add an alias with `WakeUp = 0xE063`.

**Comment by developer91234** [comment]
Could also call it Fn. That's what it's labelled on the keyboard.

**Comment by houmain** [comment]
I will go with WakeUp, since that is also what [Chrome](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values) calls it.
