### ISSUE TITLE
Dual use keys

### ISSUE THREAD

**Issue by developer91234** [houmain/keymapper#195]
This is probably addressed in the README but I tried a bunch of things and just can't figure out how to do the following:

```
# Meta alone types t on release, stupid example for demonstration purposes
Meta    >> ^T
# Meta together with another works as a modifier: this works but types T upon release.
Meta{Any} >>  Meta{Any}^
# Optionally, one exception is made: this only works if placed before the Meta{Any} mapping. Not sure if there is any way to do it so that it works even if placed after the second mapping.
Meta{X}   >> Alt{Tab}^
```

What's the proper way to this so that the T output is suppressed on release when Meta used as a modifier? I've tried Meta{!Any} >> ^T but it throws an error.

**Comment by developer91234** [comment]
I see there's a section on no key involving timing but this isn't what I'm going for here. Either a depressed key is followed up by some other key(s) before it's released or it's not, timing is irrelevant. This is the principle behind a bunch of utilities like XCape etc, so that a key like Space can act as both Space and a modifier.

**Comment by ristomatti** [comment]
I'm not sure if I quite understand what you are trying to do, but could this be what you want?

```ini
# Output Alt+Tab on Meta+x
Meta{X}   >> !Any Alt{Tab}

# Retain Meta as modifier
Meta{Any} >> Meta{Any}

# Meta outputs "t" on release
Meta      >> ^T

# ...or just Meta outputs "t"
Meta      >> T
```

That migth break shortcuts like `Meta+Shift+a`. If it does, try adding this at the top of the config:

```ini
@forward-modifiers Shift Control Alt
```

Alternative approach:

```ini
# Meta outputs "t" on release if held down less than 200ms
Meta{!200ms} >> ^T

# Output Alt+Tab on Meta+x
Meta{X}      >> !Any Alt{Tab}
```

**Comment by developer91234** [comment]
Yeah my bad, didn't even see the discussion section.

**Comment by developer91234** [comment]
just a last quick question here @ristomatti if that's OK, wouldn't `@forward-modifiers Meta` remove the need for the `Meta{Any} >> Meta{Any}` mapping? This extra mapping would seem a little verbose.

**Comment by ristomatti** [comment]
Possibly, just try. :) I mostly comment on my tablet w/o testing the suggestions myself.
