### ISSUE TITLE
missing versions on chocolatey

### ISSUE THREAD

**Issue by kbilsted** [houmain/keymapper#196]
hi. the latest version is 4.7.1 on chocolatey, have the deployment pipeline integration stopped working?

**Comment by houmain** [comment]
Thanks for the reminder. There is no pipeline yet, I still have to do it manually. It is already [under review](https://community.chocolatey.org/packages/keymapper/4.9.1).

**Comment by kbilsted** [comment]
Thanks.. well... i got lost in wanting to implement modal modes in applications. It didn't work and I never tried narrowing down the bug... maybe THIS TIME I will try to prove the existence of this bug! Also look at this beauty! https://www.8bitdo.com/retro-mechanical-keyboard-c64/

**Comment by ristomatti** [comment]
While not practical for my usage (I considering a true split someday, not that I've got  used to Alice layout), but it really looks pretty damn nicely made. I specifically like the Roland TR-606 / TB-303 vibe off the knobs! I'll pass the link to my (still active) C64 demoscene colleagues. :+1:

If you enjoy C64 retro stuff, you might enjoy what one of these collegues has done. Such as the [DS/DJ-2000 mk1 Alpha](https://csdb.dk/release/?id=201357) chip tune DJ software for C64 or the demo [Kauas pilvet scrollaavat](https://www.youtube.com/watch?v=gEYtEs1xee0) (the name is a play of words of the somewhat famous Aki Kaurismäki movie "Kauas pilvet karkaavat" (English title "Drifting clouds").
