### ISSUE TITLE
CapsLock >> None

### ISSUE THREAD

**Issue by boop5** [houmain/keymapper#197]
Is it possible to disable an key entirely? I want to disable CapsLock. In the msft PowerToys remapper you can do that. But I like your mapper way more!

**Comment by kbilsted** [comment]
You should really consider mapping it to ENTER, BACKSPACE or CONTROL - a key you press a lot. I've mapped two keys on CAPS LOCK one for click (ESC) and hold (CTRL). It takes practice but its worth it.

**Comment by houmain** [comment]
>  I want to disable CapsLock.

`CapsLock >> ` should do the trick.
