### ISSUE TITLE
The keymapper doesn't work with the "awesome" window manager.

### ISSUE THREAD

**Issue by miroshQa** [houmain/keymapper#198]
Why doesn't the keymapper work when using awesome wm? Is there a way to fix this?
For example, everything works on i3 wm, and of course KDE and GNOME.

**Comment by miroshQa** [comment]
Sorry, it is a shame. I started the keymapper manually and everything works. Thank you!

**Comment by ristomatti** [comment]
You can try starting it as a systemd user service. Something like this:

```ini
# Add to: .config/systemd/user/keymapper.service

[Unit]
Description=keymapper service
Wants=graphical.target
After=graphical.target keymapperd.service 

[Service]
Type=simple
Restart=on-failure
RestartSec=3
ExecStart=/usr/bin/keymapper --update

[Install]
WantedBy=default.target
```

Then run (as normal user):

```
# Make systemd detect the new service file
systemctl --user daemon-reload

# Enable service for automatic startup and start it in one go
systemctl --user enable --now keymapper.service
```

This is how I have it configured, but TBH I haven't quite figured out what should I add to sections `Wants` and/or `After` as I always have to do `systemctl --user restart keymapper` for it to start working.
