### ISSUE TITLE
Hide keymapper tray icon from config file

### ISSUE THREAD

**Issue by mfinelli** [houmain/keymapper#206]
Related to https://github.com/houmain/keymapper/issues/133 (it works to edit the keymapper.desktop file to add the `--no-tray` option) but everytime that I update the package I need to remember to edit the `/etc/xdg/autostart/keymapper.desktop` file again so that the icon is hidden. It would be nice if there was a more permanent way to hide the icon (via config file or something) that would persist through package upgrades

**Comment by ristomatti** [comment]
If I read this correctly, you should be able to create a `.desktop` file that overrides the `Exec` line with different arguments: https://wiki.archlinux.org/title/XDG_Autostart

**Comment by mfinelli** [comment]
This works copying the contents of `/etc/xdg/autostart/keymapper.desktop` into `~/.config/autostart/keymapper.desktop` with the `--no-tray` option enabled. Cheers!
