### ISSUE TITLE
Will it handle mouse clicks?

### ISSUE THREAD

**Issue by llbook** [houmain/keymapper#22]
Is there, or will there ever be, a way to capture and produce mouse clicks (like AutoHotkey does)?
Like, for instance, turning an Alt-LeftClick into a Shift-Control-LeftClick?
Anyway, thanks for an essential and already great program!

**Comment by houmain** [comment]
There is currently no way.
I will add it to my todo list (it might take a few weeks until I get to it).
Thank you for the suggestion and your kind words!

**Comment by obtuse-whoosh** [comment]
Any updates on this? I am looking for this functionality as well

**Comment by houmain** [comment]
I am glad you asked because I have good news. There will be a major release in the next few days, which supports mapping mouse buttons!

**Comment by houmain** [comment]
Hi, this is now testable. There is a [2.1.0](https://github.com/houmain/keymapper/releases/tag/2.1.0) release, which is currently still a "Pre-release".

**Comment by Zireael07** [comment]
Which mouse buttons are supported? Is it only the standard two or three, or can I use/simulate it with a multi button gaming mouse?

**Comment by ristomatti** [comment]
@Zireael07 By default there are named mappings for `ButtonLeft` (1), `ButtonRight` (3), `ButtonMiddle` (2), `ButtonBack` (8), `ButtonForward` (9), `Wheelup` (4), `WheelDown` (5), `WheelLeft` (6) and `WheelRight` (7). This does not prevent from adding aliases to additional buttons if they just send a keycode that can be mapped to.

For instance my Logitech G502 mouse has s thumb button which shows up as button 10 when testing with `xev` on Linux. This might be mouse specific, but in my case it's key event 277. I have configured an alias for it:
```
ButtonSide = 277
```

I use it a lot. Mostly as a modifier for other mouse buttons.
