### ISSUE TITLE
gnome 42 support

### ISSUE THREAD

**Issue by mfinelli** [houmain/keymapper#27]
GNOME 42 recently landed in the arch repositories, and so the gnome extension that you added is "incompatible". I think that it should be enough to add `42` to the shell-version in this file https://github.com/houmain/keymapper/blob/main/extra/share/gnome-shell/extensions/keymapper%40houmain.github.com/metadata.json and then make a release. Cheers

**Comment by houmain** [comment]
Thanks for reporting. 
I am thinking about adding the next few versions to the list.
