### ISSUE TITLE
An ability to hide tray icon

### ISSUE THREAD

**Issue by Azarattum** [houmain/keymapper#31]
It would be nice to have an option like `-n, --notray` to tell the program not to show the tray icon introduced in [2.1.1](https://github.com/houmain/keymapper/releases/tag/2.1.1). I personally like to have `keymapper` silently running in background as if it's a part of an operating system. I rarely touch the config, exit or reload the program. It just runs and does it's job.

Since this is just a **personal preference**, I agree that no icon should not be default. Although having such flag would be really neat.

**Comment by houmain** [comment]
Thanks for the suggestion, this is implemented now.
