### ISSUE TITLE
Long press support

### ISSUE THREAD

**Issue by niwla23** [houmain/keymapper#32]
Add a syntax and feature to handle a key long press. Would be useful for action keys. (e.g. turning lights on or off, ctrl c/v)

I propose a syntax like this:

```
Hold{C} >> (Control){C}
Hold{A, 3000} >> F13 // optional hold time as seconds parameter
Hold{Q} >> (Alt){F4}
```

**Comment by houmain** [comment]
Hi, this should work now in the 2.4.0 release. See [No key](https://github.com/houmain/keymapper#no-key).

**Comment by niwla23** [comment]
Thank you :heart: ! I will check it out.

**Comment by niwla23** [comment]
guess this can be closed @houmain ?
