### ISSUE TITLE
About the layout of the author's profile

### ISSUE THREAD

**Issue by yyy33** [houmain/keymapper#34]
Hello, I found the layout of your profile very beautiful, may I ask you are manually layout? Or what software do you use?

**Comment by houmain** [comment]
Thanks! I manually layouted it using a plain text editor ([Geany](https://www.geany.org) or my own editor [GPUpad](https://github.com/houmain/gpupad)). I regularly use rectangular selection (by holding Alt-Shift-Down...) to insert and remove spaces in multiple lines at once...
