### ISSUE TITLE
Bluetooth keyboard not affected

### ISSUE THREAD

**Issue by KaffeMyers** [houmain/keymapper#38]
Hi!
Got this issue with the bluetooth keyboard being ignored by keymapper (works fine, just not intercepted). Saw you wanted some `sudo evtest` logs in another thread, so trying those!
[click for log](https://gist.github.com/KaffeMyers/497ee017882afe6413f1af57ff52a0f5)

**Comment by houmain** [comment]
Hi!
Thanks for the log. These kind of problems should be finally fixed with the latest commits ([2.2.0](https://github.com/houmain/keymapper/releases/tag/2.2.0)).

**Comment by gcoda** [comment]
I just encountered this behavior. Keyboard mappings ignored after i switch keyboard to bluetooth mode.
tried both `aur/keymapper` and `aur/keymapper-git@r187.963fd63-1`

**Comment by houmain** [comment]
Hi, thanks for your comment! Maybe I closed the issue too quickly :hushed:. Could you please try `aur/keymapper` once more? I removed the quite arbitrary bus type filter.

**Comment by gcoda** [comment]
Yeah, it works!
