### ISSUE TITLE
Feature Request: Input device aware mapping (macro keyboard support)

### ISSUE THREAD

**Issue by G-M0N3Y-2503** [houmain/keymapper#4]
For my use case, I have a "Razer Naga" that has a numeric keypad on the side which maps to the keys of the number row on a standard US keyboard layout. This means In order to configure key mappings for the mouse keypad and not the number row on a keyboard there would have to be some way to filter the input expressions to a particular device.

From a configuration point of view, a `device` filter for the context block might work.
```
[device="Razer Naga"]
Digit0 >> AltLeft ArrowLeft
```
However, that wouldn't work if someone else wanted a more powerful/flexible variation of this, where they might want to filter only parts of the input expression to a particular device.

**Comment by G-M0N3Y-2503** [comment]
Otherwise, great work, this project looks almost perfect for my needs.  
If this is something that you think would be amenable for this project (and I can find the motivation to jump back into C++ again) I might be able to help out with it.

**Comment by houmain** [comment]
Thank you for your appreciation!
Your proposed addition to the context filters looks fine to me. That would be a nice feature to have, but also quite a bit of work.
On Linux the most laborious part would be to get the configuration to the daemon and on Windows usage of this feature would presumably require enabling the Interception library (https://github.com/houmain/keymapper#windows) to get information about the triggering device.
I am not sure when I would try implementing this (I might need some more use cases/votes).

**Comment by houmain** [comment]
Hi, this is now testable. There is a [2.1.0](https://github.com/houmain/keymapper/releases/tag/2.1.0) release, which is currently still a "Pre-release". The feature is currently only available on Linux and the syntax is just as you proposed.

**Comment by G-M0N3Y-2503** [comment]
That's awesome, I'll have to check this out again!

**Comment by houmain** [comment]
Fine! You should get the required exact device name using:
`cat /proc/bus/input/devices | grep Name=`
or by activating verbose output, by passing -v to keymapperd.

**Comment by G-M0N3Y-2503** [comment]
Was just trying this out today and I noticed that the device that is used when one isn't specified was my mouse rather than my keyboard or both. This was somewhat unexpected to me, perhaps documenting the default device selection would mitigate this confusion for others?

Otherwise, I would have thought that mappings with unspecified devices would match all devices. 
That is, with `1 >> 9`, `1` would map to `9` on all keyboards and mice.

**Comment by G-M0N3Y-2503** [comment]
Actually, With the following config
```
[device="Razer Razer BlackWidow Ultimate 2013"]
1 >> 9
9 >> 1

[device="Razer Razer Naga 2014"]
1 >> 9
9 >> 1
```
Only the Naga had key mapping, neither the Numrow nor Numpad was mapped on the BlackWidow.

here is some extra info if that helps:
Version: 2.1.2 from AUR

```
$ keymapperd --verbose
Waiting for keymapper to connect
Received configuration
Received contexts (2)
Creating uinput device 'Keymapper'
Updating device list
Grabbing device event3 'Razer Razer BlackWidow Ultimate 2013'
Grabbing device event9 'Razer Razer Naga 2014'
Entering update loop
Received contexts (2)
Received contexts (2)
Connection to keymapper reset
Ungrabbing device event3
Ungrabbing device event9
---------------
```

```
$ keymapper --verbose --update
Loading configuration file '/home/gerard/keymapper.conf'
Connecting to keymapperd
Sending configuration
Initializing focused window detection
Initialized X11 focused window detection
Initialized D-BUS focused window detection
Entering update loop
Detected focused window changed:
class = 'konsole'
title = '~ : bash — Konsole'
Detected focused window changed:
class = 'konsole'
title = '~ : keymapper — Konsole'
```

**Comment by G-M0N3Y-2503** [comment]
I found the cause for this It seems that the wrong uinput device is used by keymapper.
Sorry for the noise, this looks more like https://github.com/houmain/keymapper/issues/29 now.
```
lrwxrwxrwx 1 root root 9 Jun 18 20:09 /dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate_2013-event-kbd -> ../event3
lrwxrwxrwx 1 root root 9 Jun 18 20:09 /dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate_2013-if01-event-kbd -> ../event4
lrwxrwxrwx 1 root root 9 Jun 18 20:09 /dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate_2013-if02-event-mouse -> ../event6
lrwxrwxrwx 1 root root 9 Jun 18 20:09 /dev/input/by-id/usb-Razer_Razer_BlackWidow_Ultimate_2013-if02-mouse -> ../mouse0
```
The device that outputs the events for me is the `if01-event-kbd` one.

**Comment by G-M0N3Y-2503** [comment]
I was looking at the Win32 [Raw Input Overview](https://learn.microsoft.com/en-us/windows/win32/inputdev/about-raw-input) and it looks like you can get a device name with [GetRawInputDeviceInfoA](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdeviceinfoa) and map it to raw inputs. Might not be worth the effort for this in windows still, I was curious and just had a breif look.
