### ISSUE TITLE
[suggestion] Add a timeout function to achieve xcape-like effects

### ISSUE THREAD

**Issue by yyy33** [houmain/keymapper#40]
For example, I have the following two mappings, which implement the function of sending `esc` with a click of `ctrl`,But I want the second mapping to take effect only when I press the key and release it within 500ms, and nothing if it exceeds 500ms.
In the actual use of the process, I think this timeout is quite helpful, otherwise often will accidentally touch the esc key
```
ControlLeft{Any} >> ControlLeft{Any}
ControlLeft >> Escape
```

**Comment by yyy33** [comment]
> 

Great!

**Comment by yyy33** [comment]
> Thanks for the suggestion. Never heard of [xcape](https://github.com/alols/xcape) or thought about this use case. Seems to be quite prevalent. There is another similar request #32. I will think about how this could be achieved.

Great!

**Comment by houmain** [comment]
Hi, this should work now in the 2.4.0 release. See [No key](https://github.com/houmain/keymapper#no-key).

**Comment by yyy33** [comment]
> Hi, this should work now in the 2.4.0 release. See [No key](https://github.com/houmain/keymapper#no-key).

Great, thanks for your hard work!
