### ISSUE TITLE
bad_alloc in keymapper binary

### ISSUE THREAD

**Issue by niwla23** [houmain/keymapper#45]
I get the following error when running `keymapper` on fedora 36:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    56284 IOT instruction (core dumped)  keymapper -v
```

I have attached the strace.
[keymapper-stracer.txt](https://github.com/houmain/keymapper/files/9777293/keymapper-stracer.txt)

**Comment by niwla23** [comment]
I am using the prebuilt version from GH Releases

**Comment by houmain** [comment]
Thanks for reporting! I just noticed that the binaries built by the build server do not work on my machine either. It crashes on the first harmless allocation. :cry: 
Version 1.10.0 works, 2.1.0 crashes. But the build process did not change, as far as I can tell.

**Comment by houmain** [comment]
The build server uses quite an old gcc, where one had to link a filesystem library. This was missing and resulted in a runtime crash but is fixed now!

**Comment by niwla23** [comment]
Great to hear, I will try the new binary later
