### ISSUE TITLE
Keyboard modifiers stuck if pressed with mouse of specific model

### ISSUE THREAD

**Issue by gcoda** [houmain/keymapper#48]
Reporting this just "in case", it is really bizarre, and i "fixed" it by using mouse in Bluetooth mode :smiley: .

Modifier key not sending `KEY_UP` event right away.
Longer i hold - longer its getting stuck, not even noticeable on short clicks.
Tried lowering polling rate of a mouse, since Bluetooth is lower, same result.

It only happening on specific mouse:
`046d:c539 Logitech, Inc. Cordless Mouse Receiver`

Another mouse by Logitech `046d:c52b` - fine
Same mouse in Bluetooth mode - works fine
Another mouse - of course fine
Happens with any keyboard.
Happens with empty config

**Comment by houmain** [comment]
Thanks for reporting, this is very interesting! 
So Shift and Control are longer down than physically pressed, despite the configuration is empty and only when this mouse is attached?
I have no idea. Maybe you could post the output of `sudo evtest` of the mouse device, when it is in Bluetooth mode and when it is not? Thanks!
