### ISSUE TITLE
Unable to keep same key pressed multiple times

### ISSUE THREAD

**Issue by RichardFevrier** [houmain/keymapper#50]
Let's take this configuration for example:

```
Meta >> Control
Control >> Meta
```

If we keep pressing without releasing the `Meta` key to perform multiple `Undo` as `Ctrl+Z` for example, it is not resolving anything the second, third, etc... times, so multiple `z` are performed (and written in a document).

**Comment by houmain** [comment]
Sorry, I cannot reproduce that. Does your configuration contain any other mappings?
