### ISSUE TITLE
CapsLock not working.

### ISSUE THREAD

**Issue by A-Lamia** [houmain/keymapper#53]
it seems i can't get `CapsLock{250ms} >> ControlLeft` working correctly nothing happens, but if i do `CapsLock{250ms} >> Tab` it works fine.

OS: Windows 10

**Comment by houmain** [comment]
Well, it does work, just not as one would expect. The Control is (as the Tab) only pressed and released quickly.
But I changed this now and made another release 2.4.1. Thanks for reporting!

**Comment by A-Lamia** [comment]
Works great thanks!
