### ISSUE TITLE
In alacritty the keystroke sequence is truncated

### ISSUE THREAD

**Issue by yyy33** [houmain/keymapper#54]
This is the minimum configuration, when I press shift plus enter in alacritty, I only get `shift-crkabc`.
I have tested it in other applications and can get the full sequence

````
tt = S H I F T Minus C R K A B C D E F G H I J K
[system="Linux" class="Alacritty" modifier="ShiftLeft"]
Enter >>  tt
````

**Comment by houmain** [comment]
Sorry, I cannot reproduce that. Even the following configuration outputs all keys to Alacritty (6x as many keys):
```
tt = S H I F T Minus C R K A B C D E F G H I J K
[system="Linux" class="Alacritty" modifier="ShiftLeft"]
Enter >>  tt tt tt tt tt tt 6
```
Are you on Wayland? I tested on X11.

**Comment by yyy33** [comment]
> Sorry, I cannot reproduce that. Even the following configuration outputs all keys to Alacritty (6x as many keys):
> 
> ```
> tt = S H I F T Minus C R K A B C D E F G H I J K
> [system="Linux" class="Alacritty" modifier="ShiftLeft"]
> Enter >>  tt tt tt tt tt tt 6
> ```
> 
> Are you on Wayland? I tested on X11.

yes, i am useing x11 , this is my info
```
❯ pacman -Q keymapper
keymapper-git r215.a8e8e61-1
❯ pacman -Q alacritty
alacritty 0.11.0-2
❯ pacman -Q xorg-server
xorg-server 21.1.4-1
❯ uname -a
Linux x550vc-yyy 6.0.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 29 Oct 2022 14:08:39 +0000 x86_64 
Linux

```

**Comment by yyy33** [comment]
> Sorry, I cannot reproduce that. Even the following configuration outputs all keys to Alacritty (6x as many keys):
> 
> ```
> tt = S H I F T Minus C R K A B C D E F G H I J K
> [system="Linux" class="Alacritty" modifier="ShiftLeft"]
> Enter >>  tt tt tt tt tt tt 6
> ```
> 
> Are you on Wayland? I tested on X11.

I tested it in xterm and it was also truncated, but not in crhomium

**Comment by yyy33** [comment]
> Sorry, I cannot reproduce that. Even the following configuration outputs all keys to Alacritty (6x as many keys):
> 
> ```
> tt = S H I F T Minus C R K A B C D E F G H I J K
> [system="Linux" class="Alacritty" modifier="ShiftLeft"]
> Enter >>  tt tt tt tt tt tt 6
> ```
> 
> Are you on Wayland? I tested on X11.

Maybe fcitx5 is the cause of this problem, I have submitted issues

**Comment by yyy33** [comment]
> Sorry, I cannot reproduce that. Even the following configuration outputs all keys to Alacritty (6x as many keys):
> 
> ```
> tt = S H I F T Minus C R K A B C D E F G H I J K
> [system="Linux" class="Alacritty" modifier="ShiftLeft"]
> Enter >>  tt tt tt tt tt tt 6
> ```
> 
> Are you on Wayland? I tested on X11.

I upgraded to xcb-imdkit 1.0.4, the keystrokes will not be truncated by fcitx5 now, thanks https://github.com/fcitx/fcitx5/issues/676#issuecomment-1333275391
