### ISSUE TITLE
Repeating ButtonLeft 

### ISSUE THREAD

**Issue by sobornostea** [houmain/keymapper#55]
Hi !

For a videogame I wanted to do this remap (KeyK >> ButtonLeft) unfortunately the input seems to be buffered when I type it too fast which leads to it being repeated even after I stop pushing the keys. This doesn't seem to be specific to the game (I can reproduce the behaviour outside of it) but it makes me unable to use the program

**Comment by houmain** [comment]
Hi!
I could not reproduce this yet. Are you using the Windows or Linux version?
Do you have more mappings? If yes, does it also happen if you reduce your configuration to this one mapping?
Thanks!

**Comment by sobornostea** [comment]
Hi !

It seems to work now :thinking: , I've been using the following configuration on the Linux version :

```
Shift   >> Shift
Control >> Control
AltLeft >> AltLeft

KeyJ >> Space
KeyK >> ButtonLeft
AltRight >> Shift
```
