### ISSUE TITLE
Initializing Wayland window detection failed: wlr-foreign-toplevel not available

### ISSUE THREAD

**Issue by edanweis** [houmain/keymapper#56]
I cannot start keymapper. Restarting `keymapperd` doesn't help:

```
keymapper -u -c /home/ubuntu/.config/keymapper.conf
ERROR: Initializing Wayland window detection failed: wlr-foreign-toplevel not available
```
I'm running wayland on
Ubuntu 22.04.1 LTS
5.15.0-60-generic x86_64

Any suggestions?

**Comment by houmain** [comment]
Hi! 
The error message tells me that you are using an older version (it was removed in 2.4.0).
Have you tried the current version 2.4.1?

**Comment by edanweis** [comment]
Hi @houmain, after two restarts, it seems to be working again. I'll upgrade and re-open the issue if it happens again.
