### ISSUE TITLE
Launch programs or commands through keymapper

### ISSUE THREAD

**Issue by rp1231** [houmain/keymapper#64]
It would be great to have a feature to launch programs via key combos or launch commandline commands with this program.
Thanks

**Comment by houmain** [comment]
Hi, I think this feature is already implemented. 
Did you see [Terminal command binding](https://github.com/houmain/keymapper#terminal-command-binding)? 
Do you have a suggestion for improving the documentation?

**Comment by houmain** [comment]
You can only load one config at once, but on Linux you can add specific mappings for each device using:
`[device="Some Device Name"]`
See [Context awareness](https://github.com/houmain/keymapper#context-awareness).
On Windows unfortunately not.

**Comment by houmain** [comment]
Yes, absolutely.

**Comment by houmain** [comment]
True, sorry, I clarified that. Thanks!
