### ISSUE TITLE
Unexpected output delay with mouse + keyboard

### ISSUE THREAD

**Issue by G-M0N3Y-2503** [houmain/keymapper#65]
Running 2.5.1 on linux, If I use the following config
```
# Mouse
[device="Razer Razer Naga 2014"]
ButtonBack >> LaunchApp1
Any >> Any

# Keyboard
[device="Razer Razer BlackWidow Ultimate 2013"]
Any >> Any
```
Then in a text editor spam a keyboard button like `A` and the mouse button `ButtonLeft` simultaniousely.
It seems that keymapper slows to a crawl and all the inputs are buffered in order and gradually output  for up to a couple of seconds after I have stoped pressing any inputs.

This becomes obvious when playing games like an FPS with keymapper running.

**Comment by houmain** [comment]
Hi, this was intended as a feature to prevent accidental selection, when sending mouse buttons to quickly. 
I made this optional now (by adding a keymapperd parameter). 
Please try version 2.6.1.

**Comment by G-M0N3Y-2503** [comment]
I was being lazy and waited for the update to hit AUR but that appears to have fixed this, Thanks!
