### ISSUE TITLE
Exiting the app doesn't close the keymapperd.exe process

### ISSUE THREAD

**Issue by rp1231** [houmain/keymapper#66]
Exiting the app doesn't close the keymapperd.exe process

**Comment by houmain** [comment]
Hi,
When keymapper is closed, keymapperd does not do anything but wait for another keymapper to connect and send the new configuration.
This is working as intended. I do not think, this is an issue.

**Comment by houmain** [comment]
For me the installer always worked for updating a running installation. 
The "keymapper.exe and keymapperd.exe still running" dialog appeared twice. After clicking the close process button twice the installer finished as expected. Maybe I can improve that (the installer should already close them automatically).
Would be interesting to know, if another application requires both processes to exit. Would be nice if you could post it, if you experience it again.
