### ISSUE TITLE
2.6.1 fails to compile on archlinux

### ISSUE THREAD

**Issue by mfinelli** [houmain/keymapper#69]
system is up-to-date, here are my cmake and g++ (gcc) versions, let me know if you need other versions or something else

```
cmake version 3.26.4
```

```
g++ (GCC) 13.1.1 20230429
```

build log attached

[keymapper-2.6.1-1-x86_64-build.log](https://github.com/houmain/keymapper/files/11592481/keymapper-2.6.1-1-x86_64-build.log)

**Comment by houmain** [comment]
Hi Mario, thanks for reporting!
The indirectly included headers changed in gcc 13. This is fixed now.
