### ISSUE TITLE
Control + Click mouse shortcut does not work

### ISSUE THREAD

**Issue by RiccardoBarbieri** [houmain/keymapper#70]
I created this configuration
```
Shift   >> Shift    
Control >> Control    
AltLeft >> AltLeft    
    
[class="microsoft-edge"]    
Control{ArrowDown} >> Control{Tab}    
Control{ArrowUp} >> Control{Shift{Tab}}    

```
and it renders the Ctrl+click mouse shortcut to open urls in a new tab non functional.

**Comment by RiccardoBarbieri** [comment]
To get the window class I use xprop, that tells me that the browser has a `class=Microsoft-Edge` or `class=microsoft-edge`.
Using the title you proposed it does not work at all.

I want to add that I use i3wm but I don't know if it can cause problems.

**Comment by RiccardoBarbieri** [comment]
I tried restarting a couple of times and modify the way the process autostarts and now it works, I won't close the isse for another day, to test further if the issue repeats, otherwise I will close it.

**Comment by houmain** [comment]
Oh, because of Edge I assumed you are on Windows. I only tried it there.
Thanks for further testing and reporting!
