### ISSUE TITLE
Feature Request: Use path or command line context for currently running binary/exe

### ISSUE THREAD

**Issue by stealthgyro** [houmain/keymapper#71]
Switching to a QMK/VIA keyboard I've been looking for the right solution for context aware game profiles. There's a lot out there, but I really like where this project is heading. I know getting the path in windows for the window in the foreground is possible, but I don't know how much more taxing it is etc. 

I started playing around with the idea of getting the path, but I've never touched C++ so I just kept running into hurdles.

https://github.com/houmain/keymapper/compare/main...stealthgyro:keymapper:croyer-path-support

Also if you, I'll gladly donate, I didn't see any links.

**Comment by houmain** [comment]
Hi, thank you for the groudwork! I will complete this in the next few days.

**Comment by houmain** [comment]
Hi, this is implemented now in 2.7.0.
