### ISSUE TITLE
ERROR: terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by YMan84** [houmain/keymapper#72]
keymapper crashes and I get the following error message whenever i launch KeePassXC

```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string: construction from null is not valid
Aborted (core dumped)

```

I tried the native install, and also a flatpak install and they both give the same result. I'm not sure if this is an issue with keymapper or KeePassXC, as this doesn't happen when launching any other application.

System:
Operating System: EndeavourOS (Arch Linux)
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.10-arch1-1 (64-bit)
Graphics Platform: X11

KeePassXC Version: 2.7.6

**Comment by houmain** [comment]
Thank you very much for the thorough report! I could quickly reproduce and fix it.
