### ISSUE TITLE
Button toggle

### ISSUE THREAD

**Issue by TheMasterDingo** [houmain/keymapper#75]
I am trying to set up a config where i press a certain combination of buttons once to have it hold a certain button indefinitely until next press of said combination .

(group of buttons) >> F13 for example
I tried to map the input to Virtual1 and then virtual1 to F13 since it gets toggled but it does not work.

Is there a way to do it?

**Comment by houmain** [comment]
Hi, currently there is no way to do this.
I think your idea of mapping a virtual key, which is already toggled, is great!
I will try to implement this in the next time.

**Comment by TheMasterDingo** [comment]
Understood.
And thank you for this great piece of software

**Comment by houmain** [comment]
This is now available. Currently in the [3.0.0](https://github.com/houmain/keymapper/releases/tag/3.0.0) prerelease.

**Comment by TheMasterDingo** [comment]
Thank you for the heads up!
I tested it and it works very well. Im using F13 for my PTT in many games(it's bound to a button on the mouse).
Basically sometimes i want to keep the channel open so this is very usefull now. Here is the config.

(AltRight BracketRight) >> Virtualkey1
Virtualkey1 >> F13
Virtualkey1{F13} >> Virtualkey1

Basically pressing (AltRight BracketRight) toggles ON Virtualkey1 and at the same time to keep F13 pressed.
I wanted it also so when i press the physical F13 to toggles OFF Virtualkey1.
Works very well, thanks again
