### ISSUE TITLE
Support for Gnome 45

### ISSUE THREAD

**Issue by mfinelli** [houmain/keymapper#76]
With the release of Gnome 45 (now in the official Arch repositories) the gnome-shell extension that makes this work is no-longer compatible.

It seems that Gnome has changed the way that they handle the javascript in extensions: https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

The actual error message that I receive when I open the extensions settings is `extensionModule.default is not a constructor`.

**Comment by houmain** [comment]
Thanks for reporting with the helpful link!
It should work again in version 2.7.2.

**Comment by mfinelli** [comment]
Yes, with version 2.7.2 this is working again! Thanks!
