### ISSUE TITLE
[SUGGESTION] Launching applications hidden

### ISSUE THREAD

**Issue by TheMasterDingo** [houmain/keymapper#79]
Currently i am using 2 software, keymapper and hotkeyD. Both work very well but i was thinking that keymapper already does what hotkeyD does. It launches applications(also scripts) through hotkeys. The only thing it misses is the possibility for it to launch them hidden, it is very useful for scripts in particular to hide the console. I have certain hotkeys to launch scripts to change settings on my pc( default audio device, monitor state, etc).

So what i am suggesting here is to add the possibility to launch the applications hidden.
Link to hotkeyD, maybe it's easier for the dev to see how he does it : https://github.com/HikariKnight/hotkeyD

Thank you

**Comment by houmain** [comment]
Hi!
With version 3.1.0 all console applications are hidden by default (cmd and powershell were the only exceptions). 
To reveal them one can prepend a start e.g. `$(start cmd)`.
