### ISSUE TITLE
KDE Wayland: not detecting window attributes

### ISSUE THREAD

**Issue by 1player** [houmain/keymapper#80]
```
% ./keymapper -v -u
Loading configuration file '/var/home/sph/.config/keymapper.conf'
Connecting to keymapperd
Sending configuration
Initializing focused window detection:
  X11 support: initialized
  D-BUS support: initialized
  wlroots support: not available
Entering update loop
Configuration updated
Detected focused window changed:
  class = ''
  title = ''
  path = ''
```

The focused window is GNU Emacs with class `emacs`. Wayland support is compiled correctly, as shown by cmake. 
```
-- Checking for module 'dbus-1'
--   Found dbus-1, version 1.14.10
-- Checking for module 'wayland-client>=1.13.0'
--   Found wayland-client, version 1.22.0
```

Tested with the latest code from master.

**Comment by 1player** [comment]
Ah, looks like KDE has its own Wayland protocol to do that... https://wayland.app/protocols/kde-plasma-window-management

If I was more comfortable with C++ I would attempt to write a PR, but for now I leave it to more experienced hands.

**Comment by 1player** [comment]
I've spent a few minutes trying to add support for that protocol, but I do not see exported on a live KDE system. Perhaps because it says it can only be bound to one client at a time.

I noticed there's a `org.kde.KWin.queryWindowInfo` DBus method, which returns all the information we need:

![Screenshot_20231116_113204](https://github.com/houmain/keymapper/assets/690120/1605e85c-3acd-4553-9fe8-82d1937b3f26)

But sadly this is only for interactive use. There is a `getWindowInfo` method as well that takes a window UUID, but I don't see any way of listing all windows in the first place. Why is this so needlessly complex...

I reckon the viable approach is to replicate what you're doing for GNOME, and create a custom KWin script that interacts with the Keymapper DBus server. Listing the active window from there should be easy enough. See https://old.reddit.com/r/kde/comments/vjv321/how_to_get_window_nameclass_in_kde_wayland/idlfhs0/ and https://old.reddit.com/r/kde/comments/vjv321/how_to_get_window_nameclass_in_kde_wayland/idlfhs0/

I'm not sure when I'll have the time to work on that, but this should be enough information to get started if anyone wants to have a crack at it.

**Comment by houmain** [comment]
Hi, thank you very much for your contributions!
This was already on my TODO list.

I stumbled over this [kwin-script.js](https://github.com/k0kubun/xremap/blob/master/src/client/kwin-script.js) from the xremap project.

For keymapper it likely will be:
```
workspace.clientActivated.connect(function(client){
    callDBus(
        "com.github.houmain.Keymapper",
        "/com/github/houmain/Keymapper",
        "com.github.houmain.Keymapper",
        "WindowFocus",
        "caption" in client ? client.caption : "",
        "resourceClass" in client ? client.resourceClass : ""
    );
});
```
But there is also some [rust code](https://github.com/k0kubun/xremap/blob/master/src/client/kde_client.rs), so I do not know if putting the .js somewhere is enough...
From what I can see [here](https://develop.kde.org/docs/plasma/kwin/) a script and a metadata.json should be enough. 
Maybe you could figure that out?

**Comment by alchzh** [comment]
I confirmed in `plasma-interactiveconsole` that this script works. The extra code is there to load the script into KWin, but another option is packaging the script per https://develop.kde.org/docs/plasma/kwin/ into a regular script and installing it from system settings.

**Comment by houmain** [comment]
Hi Albert, thanks for trying it out! It is now in the 3.3.0 release.
