### ISSUE TITLE
Launching applications with space

### ISSUE THREAD

**Issue by C-H-F** [houmain/keymapper#81]
Launching applications works really good as long as there are no special characters like space or plus.
It is not possible to directly start Notepad++ or VNC viewer with $().
Since the paths are
C:\Program Files\uvnc bvba\UltraVNC\vncviewer.exe
Or
C:\Program Files\Notepad++\notepad++.exe
I need to create a path variable to the application directory or open it differently.

I also tried to reproduce the problem with Calc. Copying it to D:\Temp and it works. In D:\Te mp it does not work anymore.

**Comment by houmain** [comment]
Hi C-H-F!
Thanks for reporting.
This should be fixed with version 3.1.0.
