### ISSUE TITLE
Exclude app from some global binds/mapping

### ISSUE THREAD

**Issue by TheMasterDingo** [houmain/keymapper#82]
Is there a way to exclude an app from some global bind/mapping?

I might be missing it and sorry for creating it as an issue

**Comment by houmain** [comment]
Hi, 
yes there is already a way, which is documented under [Any key](https://github.com/houmain/keymapper#any-key).

**Comment by TheMasterDingo** [comment]
Yes i have tried it that way. The problem i have is with AltLeft+Tab combination while in a game(Star Citizen).
When you hold alt+tab you can see a menu that lets you select the window by pressing tab, but when i have a config for keymapper that involves the AltLeft Key alt tab behaves differently. It seems that it can not hold the Alt eventhough i am holding it and it alt+tabs me straight to the next window. Might be because the game interferes with it with the way it captures keys?
It works fine for the rest.
I have tried this but it does not work.
Maybe you can give me an idea or smth, thanks

#games/apps-customkeys
[title="Star Citizen"]
AltLeft{Any} >> AltLeft{Any}

**Comment by houmain** [comment]
Did you try putting:
```
[title="Star Citizen"]
Any >> Any

[default]
```
at the top of your configuration file?
It only works when it is inserted before your mapping with the `AltLeft` key.

**Comment by TheMasterDingo** [comment]
Yes this way it works, it keeps everything global above the any>> any and discards anything below for that context. Thank you

**Comment by houmain** [comment]
I made the documentation more explicit. Thanks!
