### ISSUE TITLE
Gnome 45 changes for the extension got reverted

### ISSUE THREAD

**Issue by rustyCircleJones** [houmain/keymapper#93]
It looks like with the 3.1.0 release the gnome extensions reverted back to the pre-Gnome 45 version.  

Old 2.7.1 version:
https://raw.githubusercontent.com/houmain/keymapper/2.7.1/extra/share/gnome-shell/extensions/keymapper%40houmain.github.com/extension.js

3.1.0 version: 
https://raw.githubusercontent.com/houmain/keymapper/3.1.0/extra/share/gnome-shell/extensions/keymapper%40houmain.github.com/extension.js

Gnome 45-compatible 2.7.2 version: 
https://raw.githubusercontent.com/houmain/keymapper/2.7.2/extra/share/gnome-shell/extensions/keymapper%40houmain.github.com/extension.js

**Comment by houmain** [comment]
Thanks for reporting! I just made a 3.3.1 release to fix this.
