### ISSUE TITLE
Can this be used as a C++ dependency for mapping keypresses into characters (like shift+8 would become a parenthesis "(")?

### ISSUE THREAD

**Issue by ItsCubeTime** [houmain/keymapper#94]
If so, some code sample would be nice :) I realize this is somewhat off topic to the repo, so Im sorry if Im intruding slightly by opening this issue

To clarify, Im looking for a (cross-platform) simple function that takes something like a `char` and a series of booleans representing the keyboard modifier key states - and spits out a `char` that takes the modifier keys & the keyboard layout into account

Thanks
// Olliver

**Comment by houmain** [comment]
Hi Olliver,
this way round is not implemented in this project. It only determines which keys/modifiers are needed for typing specific characters. This is implemented in the StringTyper files under src/client. They might help you implementing the functionality you need.
Good luck!
